version: '3'
services:
  frontend:
    image: wnjenga/yolo-client:1.0.0
    ports:
      - 3000:3000
    stdin_open: true # Keep the terminal running
    depends_on:
      - backend
    networks:
      yolo-test-network:
        ipv4_address: 172.60.0.2
  backend:
    image: wnjenga/yolo-backend:1.0.0
    ports:
      - 5000:5000
    environment:
      MONGODB_URI: 'mongodb+srv://wnjenga:cwo1aYOmp7dr94Ky@cluster0.exzgxhs.mongodb.net/test'
    depends_on:
      - database
    networks:
      yolo-test-network:
        ipv4_address: 172.60.0.3
  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: wnjenga
      MONGO_INITDB_ROOT_PASSWORD: cwo1aYOmp7dr94Ky
    ports:
      - 27017:27017
    networks:
      yolo-test-network:
        ipv4_address: 172.60.0.4

networks:
  yolo-test-network:
    ipam:
      driver: default
      config:
        - subnet: 172.60.0.0/16