apiVersion: v1
kind: Service
metadata:
  name: yolok8s-client-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: client
  sessionAffinity: None